### ISSUE TITLE
Time series generation - returns or prices.

### ISSUE THREAD

**Issue by andrewcz** [RudyMorel/scattering_covariance#8]
Hi @RudyMorel I hope you're well.
A couple of brief questions.
- Is this designed for returns or prices (or either), as returns are mostly stationary.
- how would you generate many time series to understand the distribution of the process. 
Cheers,
Andrew

**Comment by RudyMorel** [comment]
Hi @andrewcz,

- The model implemented in this repository is stationary. 
Thus, the log-returns (which can be assumed stationary at certain granularity) should be considered.
- to generate multiple time-series you can use the "S" argument of the function "generate" from frontend.py. 

I plan to release a tutorial.ipynb to demonstrate the usage of these functions. Currently, code examples can be found in testing.ipynb

Thank you fo your questions.
Rudy

**Comment by andrewcz** [comment]
Thank you @RudyMorel! Will give it a try.

**Comment by RudyMorel** [comment]
Hi @andrewcz,

In the last commit I added a tutorial.ipynb file. 

Also, coming back to your question, I realize we may have different definitions of the word "returns". 
There are four quantities:
- the prices
- the returns (i.e. price-increments)
- the log-prices 
- the log-returns (i.e. log-price increments)

A Scattering Spectra model accepts both log-prices or log-returns. 
More generally, it accepts stationary time-series (e.g. log-returns) or time-series which are not necessarily stationary but whose increments are (e.g. log-prices).

Rudy
