### ISSUE TITLE
Version of dependencies

### ISSUE THREAD

**Issue by tamstorf** [RudyMorel/scattering_covariance#9]
Hi @RudyMorel,

Just a suggestion : In the requirements.txt file it might be helpful to add the version number for each of the packages. At the moment it may work with the latest and greatest, but over time packages tend to get out of sync and at that point it is nice to know what magic combination of versions has actually been tested and is known to work. 

Rasmus

**Comment by RudyMorel** [comment]
Hi @tamstorf,

Thank you for your suggestion.
I added a "exact_requirements.txt" file which specifies the package versions. 
I prefer not imposing exact versions in the "requirements.txt" to enable user to smoothly integrate the scatspectra package in their framework.

In the future, I may consider including the versions specified in "exact_requirements.txt" as lower bounds in the "requirements.txt", but, at this stage, they are too recent.

Rudy

**Comment by tamstorf** [comment]
Thank you ! As you point out the current versions are probably more like lower bounds than "exact requirements", but occasionally changes in one package can make it incompatible with another package even though they used to be compatible, so it is nice to know a set of package versions that have been tested together and is known to work. 

Thanks again,
Rasmus
